threshold_buy = 1
threshold_sell = -1
method = 'nesterov'

learning_rate = 0.01
momentum = 0.1
decay = 0.10
stoploss_enabled = true
stoploss_threshold = 0.85
hodl_threshold = 1
price_buffer_len = 100
min_predictions = 1000